//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollRecordServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RollRecordServiceReference.IRecordRollsService")]
    public interface IRecordRollsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/RecordRoll", ReplyAction="http://tempuri.org/IRecordRollsService/RecordRollResponse")]
        void RecordRoll(string rollStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/RecordRoll", ReplyAction="http://tempuri.org/IRecordRollsService/RecordRollResponse")]
        System.Threading.Tasks.Task RecordRollAsync(string rollStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/GetRollRecord", ReplyAction="http://tempuri.org/IRecordRollsService/GetRollRecordResponse")]
        string GetRollRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/GetRollRecord", ReplyAction="http://tempuri.org/IRecordRollsService/GetRollRecordResponse")]
        System.Threading.Tasks.Task<string> GetRollRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/SaveRollRecord", ReplyAction="http://tempuri.org/IRecordRollsService/SaveRollRecordResponse")]
        void SaveRollRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordRollsService/SaveRollRecord", ReplyAction="http://tempuri.org/IRecordRollsService/SaveRollRecordResponse")]
        System.Threading.Tasks.Task SaveRollRecordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IRecordRollsServiceChannel : RollRecordServiceReference.IRecordRollsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RecordRollsServiceClient : System.ServiceModel.ClientBase<RollRecordServiceReference.IRecordRollsService>, RollRecordServiceReference.IRecordRollsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecordRollsServiceClient() : 
                base(RecordRollsServiceClient.GetDefaultBinding(), RecordRollsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRecordRollsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecordRollsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RecordRollsServiceClient.GetBindingForEndpoint(endpointConfiguration), RecordRollsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecordRollsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecordRollsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecordRollsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecordRollsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecordRollsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void RecordRoll(string rollStr)
        {
            base.Channel.RecordRoll(rollStr);
        }
        
        public System.Threading.Tasks.Task RecordRollAsync(string rollStr)
        {
            return base.Channel.RecordRollAsync(rollStr);
        }
        
        public string GetRollRecord()
        {
            return base.Channel.GetRollRecord();
        }
        
        public System.Threading.Tasks.Task<string> GetRollRecordAsync()
        {
            return base.Channel.GetRollRecordAsync();
        }
        
        public void SaveRollRecord()
        {
            base.Channel.SaveRollRecord();
        }
        
        public System.Threading.Tasks.Task SaveRollRecordAsync()
        {
            return base.Channel.SaveRollRecordAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRecordRollsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRecordRollsService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/RecordRolls/RecordRollsService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecordRollsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRecordRollsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecordRollsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRecordRollsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRecordRollsService,
        }
    }
}
